name: theFlowiestFlow

on:
    push:
        branches:
            - 'main'

jobs: 
    docker: 
        runs-on: ubuntu-latest
        steps:
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with: 
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            - 
                name: Build and push Docker images
                uses: docker/build-push-action@v5.3.0
                with:
                    push: true
                    tags: isabwami/sabwami-project4:latest
        